using Haruka.Analyzers.Model;
using Microsoft.CodeAnalysis.Text;
using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.Diagnostics;

namespace Haruka.Analyzers;

[Generator(LanguageNames.CSharp)]
public class DependencyInjectionAnalyzer : IIncrementalGenerator
{
	private const string AutogenSourceHeader = "/// <auto-generated />\r\n";
	private static readonly SymbolDisplayFormat? s_includeGlobalNs = SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Included);

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var servicesInitial = context.SyntaxProvider.ForAttributeWithMetadataName(
			MetaDataNames.ServiceAttribute,
			(n, ct) => { ct.ThrowIfCancellationRequested();
				return n.IsKind(SyntaxKind.ClassDeclaration); },
			TransformServiceInitial)
			.WithTrackingName("Haruka.DI.CollectServices.Initial")
			.Where(m => m is not null)
			.WithTrackingName("Haruka.DI.CollectServices.Initial.NN")
			.Select((m, ct) => {
				ct.ThrowIfCancellationRequested();
				return m!.Value;
			}).Collect();

		var holders = context.SyntaxProvider.ForAttributeWithMetadataName(
			MetaDataNames.RegisterationHolderAttribute,
			(n, ct) => { ct.ThrowIfCancellationRequested();
				return n.IsKind(SyntaxKind.ClassDeclaration); },
			TransformHolder)
			.WithTrackingName("Haruka.DI.CollectHolders")
			.Where(m => m is not null)
			.WithTrackingName("Haruka.DI.CollectHolders.NN")
			.Select((m, ct) => {
				ct.ThrowIfCancellationRequested();
				return m!.Value;
			});


		var specProvider = holders.Combine(servicesInitial)
			.WithTrackingName("Haruka.DI.Combine.Holder-Service");

		context.RegisterImplementationSourceOutput(specProvider, static (ctx, spec) =>
		{
			(HolderModel holderModel, ImmutableArray<ServiceInitialModel> services) = spec;

			CancellationToken ct = ctx.CancellationToken;
			ct.ThrowIfCancellationRequested();

			holderModel.Diagnostics.TryReportDiagnostics(ctx.ReportDiagnostic, ct);
			if (holderModel.Diagnostics.IsNotEmittable || holderModel.Semantics is null)
				return;

			// holder.g.cs
			(IndentedTextWriter holderGCs, StringBuilder holderGCsSB) = SourceWriterFactory();
			HolderSemantics holder = holderModel.Semantics.Value;

			holderGCs.WriteLine();
			holderGCs.Write("namespace "); holderGCs.Write(holder.Namespace); holderGCs.WriteLine(';');
			holderGCs.WriteLine();

			string? accessibilityStr = holder.HolderSymbol.DeclaredAccessibility switch
			{
				Accessibility.NotApplicable => "",
				Accessibility.Public => "public",
				Accessibility.Internal => "internal",
				_ => null
			};

			if (accessibilityStr is null)
				return;

			string methodAccessibilityStr = holder.RegisterMethodIsIntenral ? "internal" : "public";

			// -> {acccessibilityStr} static partial class {holder.ClassName}\n
			holderGCs.Write(accessibilityStr);
			holderGCs.Write(" static partial class ");
			holderGCs.WriteLine(holder.ClassName);
			holderGCs.WriteLine('{');
			holderGCs.Indent++;

			// -> {methodAccessibilityStr} static partial void {methodName}({thisModStr}{scTypeStr} {ServicesParamName})
			holderGCs.Write(methodAccessibilityStr);
			holderGCs.Write(" static partial void GeneratedRegisterServices(");
			if (holder.ServicesParamHasThisModifier) holderGCs.Write("this ");
			holderGCs.Write($"global::{MetaDataNames.NamespaceMsExtDI}.{MetaDataNames.MSExtIServiceCollection} ");
			holderGCs.Write(holder.ServicesParamName); holderGCs.WriteLine(')');

			holderGCs.WriteLine("{");
			holderGCs.Indent++;

			string holderAccessPrefix = $"global::{MetaDataNames.NamespaceMsExtDI}.{MetaDataNames.MSExtIServiceCollection}";
			// service desciptor property identifier -> identifier used times
			Dictionary<string, int> sdPropIdentifierConflictMap = new(services.Length, StringComparer.Ordinal);


			foreach (var serviceModel in services)
			{
				(ServiceInitialSemantics? serviceNullable, ServiceDiagnostics serviceDiag) = serviceModel;

				serviceDiag.TryReportDiagnostics(ctx.ReportDiagnostic, ct);
				if (serviceDiag.IsNotEmittable)
					continue;

				Debug.Assert(serviceNullable is not null);
				var service = serviceNullable!.Value;

				try
				{
					EmitServiceServiceDescriptor(holder, service);

					string sdPropIdentifier = service.NormalizedServiceDescriptorPropertyIdentifier;
					holderGCs.Write(holder.ServicesParamName);
					holderGCs.Write(".Add(");
					holderGCs.Write(holderAccessPrefix);
					holderGCs.Write(sdPropIdentifier);
					holderGCs.WriteLine(");");
				}
				catch (HarukaICEReportedException)
				{
					throw;
				}
				catch (Exception)
				{
					ctx.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.HARUKA1007,
						holderModel.Diagnostics.HolderNameSyntaxLocation, holder.ClassName));
					throw;
				}
			}

			holderGCs.Indent--;
			holderGCs.WriteLine('}');

			holderGCs.Indent--;
			holderGCs.WriteLine('}');

			ctx.AddSource($"{holder.ClassName}.g.cs", SourceText.From(holderGCsSB.ToString(), Encoding.Unicode));
			holderGCsSB.Clear();
		});
		
		static void EmitServiceServiceDescriptor(HolderSemantics holder, ServiceInitialSemantics service)
		{
			// TODO
		}

		static ServiceInitialModel? TransformServiceInitial(GeneratorAttributeSyntaxContext gasc, CancellationToken ct)
		{
			if (gasc.Attributes.Length > 1)
				return null; // 无后续分析价值返回null

			if (gasc.TargetSymbol is not INamedTypeSymbol serviceSymbol)
				return null;

			ServiceDiagnostics diagnostics = new()
			{
				IsStaticClass = serviceSymbol.IsStatic
			};

			int genericCommaCount = serviceSymbol.Arity - 1;

			AttributeData attr = gasc.Attributes.First();
			diagnostics.AttributeContractViolation = attr.ConstructorArguments.Length != 1;

			TypedConstant attrFirstArg = attr.ConstructorArguments[0];
			diagnostics.AttributeContractViolation = attrFirstArg.Type?.MetadataName == MetaDataNames.MSExtServiceLifetime;


			TypedConstant? keyConst = null;
			if (attr.NamedArguments.FirstOrDefault(a => a.Key == "Key") is { Key: "Key", Value: TypedConstant { IsNull: false } keyConstMatch })
			{
				// 已匹配Key参数
				keyConst = keyConstMatch;
			}

			// 准备服务类型相关符号
			INamedTypeSymbol? alteredServiceTypeSymbol = null;
			// 查看是否指定了服务类型（ServiceType）			
			if (attr.NamedArguments.FirstOrDefault(a => a.Key == "ServiceType") is { Key: "ServiceType", Value: TypedConstant { IsNull: false } serviceTypeConst })
			{
				// 已匹配ServiceType参数，但需要验证其合法性
				if (serviceTypeConst.Kind != TypedConstantKind.Type)
				{
					// 编译错误：ServiceType参数必须是一个类型
					return null;
				}

				alteredServiceTypeSymbol = serviceTypeConst.Value as INamedTypeSymbol;

				if (alteredServiceTypeSymbol is null)
				{
					Debugger.Launch();
					Debugger.Break();
					return null;
				}
			}

			string serviceNamespace = serviceSymbol.ContainingNamespace?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
				?? string.Empty;

			return new ServiceInitialModel
			{
				Diagnostics = diagnostics,
				Semantics = diagnostics.IsNotEmittable ? null :
					new ServiceInitialSemantics
					{
						ServiceSymbol = serviceSymbol,
						Namespace = serviceNamespace,
						LifetimeConst = attrFirstArg,
						KeyConst = keyConst,
						AlteredServiceTypeSymbol = alteredServiceTypeSymbol
					}
			};
		}

		static HolderModel? TransformHolder(GeneratorAttributeSyntaxContext gasc, CancellationToken ct)
		{
			if (gasc.Attributes.Length > 1)
				return null; // 无后续分析价值返回null
			if (gasc.TargetSymbol is not INamedTypeSymbol holderSymbol ||
				!holderSymbol.CanBeReferencedByName)
				return null;

			INamedTypeSymbol? msExtDiIServiceCollection = gasc.SemanticModel
				.Compilation
				.GetTypeByMetadataName($"{MetaDataNames.NamespaceMsExtDI}.{MetaDataNames.MSExtIServiceCollection}");

			if (msExtDiIServiceCollection is null)
				return null;

			var syntax = (ClassDeclarationSyntax)gasc.TargetNode;

			HolderDiagnostics diagnostics = new()
			{
				IsPartial = syntax.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)),
				HolderDeclSyntax = syntax,
				HolderNameSyntaxLocation = syntax.Identifier.GetLocation(),
			};

			IEnumerable<IMethodSymbol> registerNamedMethods = holderSymbol
				.GetMembers("GeneratedRegisterServices")
				.Where(m => !m.IsImplicitlyDeclared && m.IsDefinition)
				.OfType<IMethodSymbol>();

			if (!registerNamedMethods.Any())
			{
				diagnostics.IsRegisterMethodNotDeclared = true;
				return new HolderModel
				{
					Diagnostics = diagnostics,
					Semantics = null
				};
			}

			// 生成器声明的注册方法必须满足约定，否则报错
			IEnumerable<IMethodSymbol> candidateRegisterMethods = registerNamedMethods
				.Where(m =>
					// {public/internal}
					m.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal
					// 缺少static和partial过于常见，另外检查
					// void
					&& m.ReturnsVoid
					// sig (/* this */ IServicesCollection paramName)
					&& m.Parameters.Length == 1
					&& SymbolEqualityComparer.Default.Equals(m.Parameters[0].Type,
						msExtDiIServiceCollection));

			IMethodSymbol? registerMethodSymbol = null;
			diagnostics.IsRegisterMethodNotDeclared = true;

			var invalidRegisterCandidateLocations = ImmutableArray.CreateBuilder<Location>();
			foreach (IMethodSymbol candidateRegisterMethod in candidateRegisterMethods)
			{
				// {static partial}?
				bool modifierMismatch = false;
				if (!candidateRegisterMethod.IsStatic)
				{
					diagnostics.IsRegistererNotStatic = true;
					invalidRegisterCandidateLocations.Add(candidateRegisterMethod.Locations[0]);
					modifierMismatch = true;
				}
				if (!candidateRegisterMethod.IsPartialDefinition)
				{
					diagnostics.IsRegistererNotPartial = true;
					invalidRegisterCandidateLocations.Add(candidateRegisterMethod.Locations[0]);
					modifierMismatch = true;
				}
				// 注册方法在生成前被定义
				if (candidateRegisterMethod.PartialImplementationPart is IMethodSymbol registerDef)
				{
					// 报错
					diagnostics.DefinedRegistererLocation = registerDef.Locations[0];
					continue;
				}
				if (modifierMismatch)
					continue;

				// OK
				diagnostics.IsRegisterMethodNotDeclared = false;
				registerMethodSymbol = candidateRegisterMethod;
				break;
			}

			if (registerMethodSymbol is not null && diagnostics.DefinedRegistererLocation is null)
			{
				// 清除之前设置的注册方法相关错误
				diagnostics.InvalidRegistererLocations = null;
				diagnostics.DefinedRegistererLocation = null;
				diagnostics.IsRegistererNotStatic = false;
				diagnostics.IsRegistererNotPartial = false;
			}
			else
			{
				diagnostics.IsRegistererContractViolation = diagnostics.DefinedRegistererLocation is null;
				diagnostics.InvalidRegistererLocations = invalidRegisterCandidateLocations.DrainToImmutable();
				return new(diagnostics, null);
			}

			var regPartialDefNode = (MethodDeclarationSyntax)registerMethodSymbol
				.DeclaringSyntaxReferences
				.Single()
				.GetSyntax(ct);

			diagnostics.PartialRegisterMethodNameLocation = regPartialDefNode.Identifier.GetLocation();

			if (registerMethodSymbol.ContainingType.IsExtension)
			{
				diagnostics.IsRegisterMethodInExtBlock = true;
			}

			// 所有阻止生成的错误必须在此处检查完毕，任何之后的错误都不应阻止生成
			if (diagnostics.IsNotEmittable)
				return new(diagnostics, null);

			// 错误检查完毕，准备语义信息
			string holderNamespace = holderSymbol.ContainingNamespace?.ToDisplayString()
				?? string.Empty;

			return new HolderModel
			{
				Diagnostics = diagnostics,
				Semantics = new(
					HolderDeclSyntax: syntax,
					RegisterMethodDeclSyntax: regPartialDefNode,
					HolderSymbol: holderSymbol,
					Namespace: holderNamespace,
					ClassName: holderSymbol.Name,
					ServicesParamHasThisModifier: registerMethodSymbol.IsExtensionMethod,
					ServicesParamName: registerMethodSymbol.Parameters[0].Name,
					RegisterMethodIsIntenral: registerMethodSymbol.DeclaredAccessibility == Accessibility.Internal
				)
			};
		}
	}

	private static (IndentedTextWriter, StringBuilder) SourceWriterFactory()
	{
		var builder = new StringBuilder(AutogenSourceHeader);
		return (new (new StringWriter(builder) { NewLine = "\r\n"}, "\t"), builder);
	}
}