using Haruka.Analyzers.Model;
using Microsoft.CodeAnalysis.Text;
using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.Diagnostics;

namespace Haruka.Analyzers;

[Generator(LanguageNames.CSharp)]
public class DependencyInjectionAnalyzer : IIncrementalGenerator
{
	private const string AutogenSourceHeader = "/// <auto-generated />\r\n";
	private static readonly SymbolDisplayFormat? s_includeGlobalNs = SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Included);

	private static readonly string s_harukaDiagnosticsReportedMarker = "Internal Error handled by Haruka Generator.";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var servicesInitial = context.SyntaxProvider.ForAttributeWithMetadataName(
			MetaDataNames.ServiceAttribute,
			(n, ct) => { ct.ThrowIfCancellationRequested();
				return n.IsKind(SyntaxKind.ClassDeclaration); },
			TransformServiceInitial)
			.WithTrackingName("Haruka.DI.CollectServices.Initial")
			.Where(m => m is not null)
			.WithTrackingName("Haruka.DI.CollectServices.Initial.NN")
			.Select((m, ct) => {
				ct.ThrowIfCancellationRequested();
				return m!.Value;
			}).Collect();

		var holders = context.SyntaxProvider.ForAttributeWithMetadataName(
			MetaDataNames.RegisterationHolderAttribute,
			(n, ct) => { ct.ThrowIfCancellationRequested();
				return n.IsKind(SyntaxKind.ClassDeclaration); },
			TransformHolder)
			.WithTrackingName("Haruka.DI.CollectHolders")
			.Where(m => m is not null)
			.WithTrackingName("Haruka.DI.CollectHolders.NN")
			.Select((m, ct) => {
				ct.ThrowIfCancellationRequested();
				return m!.Value;
			});


		var specProvider = holders.Combine(servicesInitial)
			.WithTrackingName("Haruka.DI.Combine.Holder-Service");

		context.RegisterImplementationSourceOutput(specProvider, EmitHolder);
		
		static void EmitHolder(SourceProductionContext ctx, (HolderModel, ImmutableArray<ServiceModel>) spec)
		{
			(HolderModel holderModel, ImmutableArray<ServiceModel> services) = spec;

			CancellationToken ct = ctx.CancellationToken;
			ct.ThrowIfCancellationRequested();

			holderModel.Diagnostics.TryReportDiagnostics(ctx.ReportDiagnostic, ct);
			if (holderModel.Diagnostics.IsNotEmittable || holderModel.Semantics is null)
				return;

			// holder.g.cs
			(IndentedTextWriter holderGCs, StringBuilder holderGCsSB) = SourceWriterFactory();
			HolderSemantics holder = holderModel.Semantics.Value;

			holderGCs.WriteLine();
			holderGCs.Write("namespace "); holderGCs.Write(holder.Namespace); holderGCs.WriteLine(';');
			holderGCs.WriteLine();

			string? accessibilityStr = holder.HolderSymbol.DeclaredAccessibility switch
			{
				Accessibility.NotApplicable => "",
				Accessibility.Public => "public",
				Accessibility.Internal => "internal",
				_ => null
			};

			if (accessibilityStr is null)
				return;

			string methodAccessibilityStr = holder.RegisterMethodIsIntenral ? "internal" : "public";

			// -> {acccessibilityStr} static partial class {holder.ClassName}\n
			holderGCs.Write(accessibilityStr);
			holderGCs.Write(" static partial class ");
			holderGCs.WriteLine(holder.ClassName);
			holderGCs.WriteLine('{');
			holderGCs.Indent++;

			// -> {methodAccessibilityStr} static partial void {methodName}({thisModStr}{scTypeStr} {ServicesParamName})
			holderGCs.Write(methodAccessibilityStr);
			holderGCs.Write(" static partial void GeneratedRegisterServices(");
			if (holder.ServicesParamHasThisModifier) holderGCs.Write("this ");
			holderGCs.Write($"global::{MetaDataNames.NamespaceMsExtDI}.{MetaDataNames.MSExtIServiceCollection} ");
			holderGCs.Write(holder.ServicesParamName); holderGCs.WriteLine(')');

			holderGCs.WriteLine("{");
			holderGCs.Indent++;

			string holderAccessPrefix = $"global::{holder.Namespace}.{holder.ClassName}.";
			// service desciptor property identifier -> identifier used times
			Dictionary<string, int> sdPropNameUsageCount = new(services.Length, StringComparer.Ordinal);


			foreach (var serviceModel in services)
			{
				(ServiceSemantics? serviceNullable, ServiceDiagnostics serviceDiag) = serviceModel;

				serviceDiag.TryReportDiagnostics(ctx.ReportDiagnostic, ct);
				if (serviceDiag.IsNotEmittable)
					continue;

				Debug.Assert(serviceNullable is not null);
				var service = serviceNullable!.Value;

				try
				{
					string? sdPropIdentifier = EmitServiceServiceDescriptor(ref ctx, holder, accessibilityStr,
						service, sdPropNameUsageCount);

					if (sdPropIdentifier is null)
						continue;
					
					holderGCs.Write(holder.ServicesParamName);
					holderGCs.Write(".Add(");
					holderGCs.Write(holderAccessPrefix);
					holderGCs.Write(sdPropIdentifier);
					holderGCs.WriteLine(");");
				}
				catch (OperationCanceledException) { throw; }
				catch (Exception ex)
				{
					if (!ex.Data.Contains(s_harukaDiagnosticsReportedMarker))
					{
						ctx.ReportDiagnostic(Diagnostic.Create(HarukaDiagnosticDescriptors.HARUKA1007,
										holderModel.Diagnostics.HolderNameSyntaxLocation, holder.ClassName));
						ex.Data.Add(s_harukaDiagnosticsReportedMarker, true);
					}
					throw;
				}
			}

			holderGCs.Indent--;
			holderGCs.WriteLine('}');

			holderGCs.Indent--;
			holderGCs.WriteLine('}');

			ctx.AddSource($"{holder.ClassName}.g.cs", SourceText.From(holderGCsSB.ToString(), Encoding.Unicode));
			holderGCsSB.Clear();
		}

		/// <returns>ServiceDescriptor属性名称</returns>
		static string? EmitServiceServiceDescriptor(ref SourceProductionContext spc, HolderSemantics holder, string holderAccessibilityStr, ServiceSemantics service, Dictionary<string, int> sdPropNameUsageCount)
		{
			string sdPropNameOriginal = service.NormalizedServiceDescriptorPropertyIdentifier;
			string sdPropName;
			if (sdPropNameUsageCount.TryGetValue(sdPropNameOriginal, out int confilctCount))
			{
				sdPropName = $"{sdPropNameOriginal}_{confilctCount}";
				sdPropNameUsageCount[sdPropNameOriginal] = confilctCount + 1;
			}
			else
			{
				sdPropName = sdPropNameOriginal;
				sdPropNameUsageCount[sdPropNameOriginal] = 1;
			}

			const string MSExtDINamespaceAccess = $"global::{MetaDataNames.NamespaceMsExtDI}.";
			(IndentedTextWriter writer, StringBuilder serviceGCsSB) = SourceWriterFactory();

			try
			{
				writer.WriteLine();
				writer.Write("namespace "); writer.Write(holder.Namespace); writer.WriteLine(';');
				writer.WriteLine();

				// -> {acccessibilityStr} static partial class {holder.ClassName}\n
				writer.Write(holderAccessibilityStr);
				writer.Write(" static partial class ");
				writer.WriteLine(holder.ClassName);
				writer.WriteLine('{');
				writer.Indent++;

				writer.Write(service.AccessibilityString ?? "public");
				writer.Write($" static {MSExtDINamespaceAccess}{MetaDataNames.ServiceDescriptor} ");
				writer.WriteLine(sdPropName);
				writer.WriteLine('{');
				writer.Indent++;

				writer.WriteLine("get");
				writer.WriteLine('{');
				writer.Indent++;

				string serviceImplReference = $"global::{service.Namespace}.{service.ClassName}" +
					$"{(service.IsSpecialGeneric ? service.GenericBracketString : "")}";
				switch (service.SDOverload)
				{
					case ServiceDescriptorOverload.NotKeyed:
						EmitServiceSdArgs_NotKeyed(ref spc, serviceImplReference, writer, service);
						break;
					default:
						spc.ReportDiagnostic(Diagnostic.Create(HarukaDiagnosticDescriptors.HARUKA2004,
							service.ClassNameLocation,
							service.ClassName));
						return null;
				}


				writer.Indent--;
				writer.WriteLine('}');

				writer.Indent--;
				writer.WriteLine('}');

				writer.Indent--;
				writer.WriteLine('}');

				spc.AddSource($"{holder.ClassName}.{sdPropName}.g.cs", SourceText.From(serviceGCsSB.ToString(), Encoding.Unicode));
				serviceGCsSB.Clear();
			}
			catch (OperationCanceledException) { throw; }
			catch (Exception ex)
			{
				if (!ex.Data.Contains(s_harukaDiagnosticsReportedMarker))
				{
					spc.ReportDiagnostic(Diagnostic.Create(HarukaDiagnosticDescriptors.HARUKA2100,
									service.ServiceDeclSyntax.GetLocation(), service.ClassName));
					ex.Data.Add(s_harukaDiagnosticsReportedMarker, true);
				}
				throw;
			}

			return sdPropName;

			static void EmitServiceSdArgs_NotKeyed(ref SourceProductionContext spc, string serviceImplReference, IndentedTextWriter writer, ServiceSemantics service)
			{
				if (!CheckServiceLifetime(ref spc, service.LifetimeConst, service.ClassNameLocation))
					return;

				writer.WriteLine($"return {MSExtDINamespaceAccess}{MetaDataNames.ServiceDescriptor}.Describe(");
				writer.Indent++;

				string? serviceReference = service.AlteredServiceTypeReferenceString
					?? serviceImplReference;
				writer.WriteLine($"typeof({serviceReference}),");
				writer.WriteLine($"typeof({serviceImplReference}),");
				string lifetimeEnumReference = EnumConstToReference(service.LifetimeConst);
				writer.WriteLine(lifetimeEnumReference);

				writer.Indent--;
				writer.WriteLine(");");
			}
		}

		static bool CheckServiceLifetime(ref SourceProductionContext spc, TypedConstant lifetimeValue, Location diagnosticLocation)
		{
			if (lifetimeValue.IsNull || lifetimeValue is not { Kind: TypedConstantKind.Enum,
				Type.MetadataName: MetaDataNames.MSExtServiceLifetime })
			{
				spc.ReportDiagnostic(Diagnostic.Create("HARUKA8001", "Haruka DI",
					"指定的服务生存期存在错误，已跳过生成", DiagnosticSeverity.Warning, DiagnosticSeverity.Warning,
					true, 1, location: diagnosticLocation));
				return false;
			}

			return true;
		}

		static string EnumConstToReference(TypedConstant constant)
		{
			Debug.Assert(constant is { Kind: TypedConstantKind.Enum, Type.TypeKind: TypeKind.Enum }, "bad invocation to EnumConstToRefrence()");
			object? underlyingValue = constant.Value;

			INamedTypeSymbol? enumType = constant.Type as INamedTypeSymbol;
			Debug.Assert(enumType is not null, "the value type is not an enum");

			string? fldName = null;
			
			foreach (var member in enumType!.GetMembers())
			{
				if (member is IFieldSymbol field &&
					field.ConstantValue != null &&
					field.ConstantValue.Equals(constant.Value))
				{
					fldName = field.Name;
					break;
				}
			}

			Debug.Assert(fldName is not null, "value is not defined in the enum");
			
			string typeFullName = enumType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
						
			return $"{typeFullName}.{fldName}";
		}

		static ServiceModel? TransformServiceInitial(GeneratorAttributeSyntaxContext gasc, CancellationToken ct)
		{
			if (gasc.TargetSymbol is not INamedTypeSymbol serviceSymbol)
				return null;
			if (gasc.TargetNode is not ClassDeclarationSyntax serviceDeclSyntax)
				return null;

			ServiceDiagnostics diagnostics = new()
			{
				IsStaticClass = serviceSymbol.IsStatic
			};


			int genericCommaCount = serviceSymbol.Arity - 1;

			if (gasc.Attributes.Length > 1)
			{
				return TransformMultipleInterfaceService(gasc, serviceSymbol, diagnostics, genericCommaCount);
			}

			AttributeData attr = gasc.Attributes.First();
			diagnostics.AttributeContractViolation = attr.ConstructorArguments.Length != 1;

			TypedConstant attrFirstArg = attr.ConstructorArguments[0];
			diagnostics.AttributeContractViolation = attrFirstArg.Type?.MetadataName != MetaDataNames.MSExtServiceLifetime;

			TypedConstant? keyConst = null;
			INamedTypeSymbol? alteredServiceTypeSymbol = null;

			foreach (KeyValuePair<string, TypedConstant> arg in attr.NamedArguments)
			{
				object? _ = arg switch
				{
					{ Key: "Key", Value: TypedConstant { IsNull: false } keyConstMatch } => keyConst = keyConstMatch,
					{
						Key: "ServiceType", Value: TypedConstant {
							IsNull: false, Kind: TypedConstantKind.Type
						} serviceTypeConst
					} => alteredServiceTypeSymbol = (INamedTypeSymbol?)serviceTypeConst.Value,
					{
						Key: "PropertyAccessibilityCSharpString", Value: TypedConstant
						{
							Kind: TypedConstantKind.Primitive, IsNull: false, Type.MetadataName: "String"
						} accessibilityStrConst
					} => diagnostics.PropAccessibilityString = (string)accessibilityStrConst.Value!,
					_ => null
				};
			}

			string serviceNamespace = serviceSymbol.ContainingNamespace?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
				?[("global::".Length)..]
				?? string.Empty;

			string className = serviceSymbol.Name;

			return new ServiceModel
			{
				Diagnostics = diagnostics,
				Semantics = diagnostics.IsNotEmittable ? null :
					new ServiceSemantics
					{
						ServiceSymbol = serviceSymbol,
						Namespace = serviceNamespace,
						ClassName = className,
						LifetimeConst = attrFirstArg,
						KeyConst = keyConst,
						GenericCommaCount = genericCommaCount,
						AlteredServiceTypeSymbol = alteredServiceTypeSymbol,
						AccessibilityString = diagnostics.PropAccessibilityString,
						ClassNameLocation = serviceDeclSyntax.Identifier.GetLocation(),
						ServiceDeclSyntax = serviceDeclSyntax
					}
			};
		}

		static ServiceModel? TransformMultipleInterfaceService(GeneratorAttributeSyntaxContext gasc, INamedTypeSymbol serviceSymbol, ServiceDiagnostics diagnostics, int genericCommaCount)
		{
			diagnostics.MultipleInterfaceNotSupported = true;
			return new(null, diagnostics);
		}

		static HolderModel? TransformHolder(GeneratorAttributeSyntaxContext gasc, CancellationToken ct)
		{
			if (gasc.Attributes.Length > 1)
				return null; // 无后续分析价值返回null
			if (gasc.TargetSymbol is not INamedTypeSymbol holderSymbol ||
				!holderSymbol.CanBeReferencedByName)
				return null;

			INamedTypeSymbol? msExtDiIServiceCollection = gasc.SemanticModel
				.Compilation
				.GetTypeByMetadataName($"{MetaDataNames.NamespaceMsExtDI}.{MetaDataNames.MSExtIServiceCollection}");

			if (msExtDiIServiceCollection is null)
				return null;

			var syntax = (ClassDeclarationSyntax)gasc.TargetNode;

			HolderDiagnostics diagnostics = new()
			{
				IsPartial = syntax.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)),
				HolderDeclSyntax = syntax,
				HolderNameSyntaxLocation = syntax.Identifier.GetLocation(),
			};

			IEnumerable<IMethodSymbol> registerNamedMethods = holderSymbol
				.GetMembers("GeneratedRegisterServices")
				.Where(m => !m.IsImplicitlyDeclared && m.IsDefinition)
				.OfType<IMethodSymbol>();

			if (!registerNamedMethods.Any())
			{
				diagnostics.IsRegisterMethodNotDeclared = true;
				return new HolderModel
				{
					Diagnostics = diagnostics,
					Semantics = null
				};
			}

			// 生成器声明的注册方法必须满足约定，否则报错
			IEnumerable<IMethodSymbol> candidateRegisterMethods = registerNamedMethods
				.Where(m =>
					// {public/internal}
					m.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal
					// 缺少static和partial过于常见，另外检查
					// void
					&& m.ReturnsVoid
					// sig (/* this */ IServicesCollection paramName)
					&& m.Parameters.Length == 1
					&& SymbolEqualityComparer.Default.Equals(m.Parameters[0].Type,
						msExtDiIServiceCollection));

			IMethodSymbol? registerMethodSymbol = null;
			diagnostics.IsRegisterMethodNotDeclared = true;

			var invalidRegisterCandidateLocations = ImmutableArray.CreateBuilder<Location>();
			foreach (IMethodSymbol candidateRegisterMethod in candidateRegisterMethods)
			{
				// {static partial}?
				bool modifierMismatch = false;
				if (!candidateRegisterMethod.IsStatic)
				{
					diagnostics.IsRegistererNotStatic = true;
					invalidRegisterCandidateLocations.Add(candidateRegisterMethod.Locations[0]);
					modifierMismatch = true;
				}
				if (!candidateRegisterMethod.IsPartialDefinition)
				{
					diagnostics.IsRegistererNotPartial = true;
					invalidRegisterCandidateLocations.Add(candidateRegisterMethod.Locations[0]);
					modifierMismatch = true;
				}
				// 注册方法在生成前被定义
				if (candidateRegisterMethod.PartialImplementationPart is IMethodSymbol registerDef)
				{
					// 报错
					diagnostics.DefinedRegistererLocation = registerDef.Locations[0];
					continue;
				}
				if (modifierMismatch)
					continue;

				// OK
				diagnostics.IsRegisterMethodNotDeclared = false;
				registerMethodSymbol = candidateRegisterMethod;
				break;
			}

			if (registerMethodSymbol is not null && diagnostics.DefinedRegistererLocation is null)
			{
				// 清除之前设置的注册方法相关错误
				diagnostics.InvalidRegistererLocations = null;
				diagnostics.DefinedRegistererLocation = null;
				diagnostics.IsRegistererNotStatic = false;
				diagnostics.IsRegistererNotPartial = false;
			}
			else
			{
				diagnostics.IsRegistererContractViolation = diagnostics.DefinedRegistererLocation is null;
				diagnostics.InvalidRegistererLocations = invalidRegisterCandidateLocations.DrainToImmutable();
				return new(diagnostics, null);
			}

			var regPartialDefNode = (MethodDeclarationSyntax)registerMethodSymbol
				.DeclaringSyntaxReferences
				.Single()
				.GetSyntax(ct);

			diagnostics.PartialRegisterMethodNameLocation = regPartialDefNode.Identifier.GetLocation();

			if (registerMethodSymbol.ContainingType.IsExtension)
			{
				diagnostics.IsRegisterMethodInExtBlock = true;
			}

			// 所有阻止生成的错误必须在此处检查完毕，任何之后的错误都不应阻止生成
			if (diagnostics.IsNotEmittable)
				return new(diagnostics, null);

			// 错误检查完毕，准备语义信息
			string holderNamespace = holderSymbol.ContainingNamespace?.ToDisplayString()
				?? string.Empty;

			return new HolderModel
			{
				Diagnostics = diagnostics,
				Semantics = new(
					HolderDeclSyntax: syntax,
					RegisterMethodDeclSyntax: regPartialDefNode,
					HolderSymbol: holderSymbol,
					Namespace: holderNamespace,
					ClassName: holderSymbol.Name,
					ServicesParamHasThisModifier: registerMethodSymbol.IsExtensionMethod,
					ServicesParamName: registerMethodSymbol.Parameters[0].Name,
					RegisterMethodIsIntenral: registerMethodSymbol.DeclaredAccessibility == Accessibility.Internal
				)
			};
		}
	}

	private static (IndentedTextWriter, StringBuilder) SourceWriterFactory()
	{
		var builder = new StringBuilder(AutogenSourceHeader);
		return (new (new StringWriter(builder) { NewLine = "\r\n"}, "\t"), builder);
	}
}