// DO NOT convert line delimiter to LF OR checkout as LF
// Generator hard coded CRLF in the writer, make this file LF will break all tests
using Microsoft.CodeAnalysis.Testing;
using VerifyCS = Haruka.Analyzers.Test.CSharpSGVerifier<Haruka.Analyzers.DependencyInjectionAnalyzer>;

namespace Haruka.Analyzer.Test;

public partial class HarukaDIGeneratorTests
{
	[Fact]
	public async Task ServicesWithGenericSingleFile()
	{
		const string sourceWithHolderAndService =
@"
using Haruka.Attributes;
using Microsoft.Extensions.DependencyInjection;

namespace Test;

[HarukaRegisterationHolder]
internal static partial class HarukaHolder
{
	internal static partial void GeneratedRegisterServices(IServiceCollection services);
}

[Service(ServiceLifetime.Singleton/*, Key = 114514*/)]
internal class Service { }

[Service(ServiceLifetime.Singleton/*, Key = 114514*/)]
internal class Service<T> { }
";
		const string test_Holder_GCs = /*lang=c#-test*/
@"/// <auto-generated />

namespace Test;

internal static partial class HarukaHolder
{
	internal static partial void GeneratedRegisterServices(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
	{
		services.Add(global::Test.HarukaHolder.Test_Service_Descriptor);
		services.Add(global::Test.HarukaHolder.Test_Service_of_1_Descriptor);
	}
}
";
		const string test_Service_GCs = /*lang=c#-test*/
@"/// <auto-generated />

namespace Test;

internal static partial class HarukaHolder
{
	public static global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor Test_Service_Descriptor
	{
		get
		{
			return global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(
				typeof(global::Test.Service),
				typeof(global::Test.Service),
				global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton
			);
		}
	}
}
";
		const string test_Service_of_1_GCs = /*lang=c#-test*/
@"/// <auto-generated />

namespace Test;

internal static partial class HarukaHolder
{
	public static global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor Test_Service_of_1_Descriptor
	{
		get
		{
			return global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(
				typeof(global::Test.Service<>),
				typeof(global::Test.Service<>),
				global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton
			);
		}
	}
}
";

		await VerifyCS.VerifyAsync(TestContext.Current.CancellationToken, sourceWithHolderAndService, [
			("HarukaHolder.Test_Service_Descriptor.g.cs", test_Service_GCs),
			("HarukaHolder.Test_Service_of_1_Descriptor.g.cs", test_Service_of_1_GCs),
			("HarukaHolder.g.cs", test_Holder_GCs)
		]);
	}
}
