// DO NOT convert line delimiter to LF OR checkout as LF
// Generator hard coded CRLF in the writer, make this file LF will break all tests
using Microsoft.CodeAnalysis.Testing;
using VerifyCS = Haruka.Analyzers.Test.CSharpSGVerifier<Haruka.Analyzers.DependencyInjectionAnalyzer>;

namespace Haruka.Analyzer.Test;

public partial class HarukaDIGeneratorTests
{
	//No diagnostics expected to show up
	[Fact]
	public async Task NoAction()
	{
		var test = @"";

		await VerifyCS.VerifyAsync(TestContext.Current.CancellationToken, test, []);
	}

	[Fact]
	public async Task EmptyBodyStaticClass()
	{
		var test = @"
using Microsoft.Extensions.DependencyInjection;
using Haruka.Attributes;

namespace Haruka.Generated.Tests;

[HarukaRegisterationHolder]
public static partial class HarukaHolder
{
	public static partial void GeneratedRegisterServices(this IServiceCollection services);
}
";
		var harukaHolderGCs = /*lang=c#-test*/@"/// <auto-generated />

namespace Haruka.Generated.Tests;

public static partial class HarukaHolder
{
	public static partial void GeneratedRegisterServices(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
	{
	}
}
";
		await VerifyCS.VerifyAsync(TestContext.Current.CancellationToken, test, [("HarukaHolder.g.cs", harukaHolderGCs)], []);
	}

	[Fact]
	public async Task EmptyClassBody()
	{
		var test = @"
	using Haruka.Attributes;

	namespace ConsoleApplication1
	{
		[HarukaRegisterationHolder]
		public class {|#0:Holder|}
		{   
		}
	}";


		var hrk1003 = DiagnosticResult.CompilerError("HARUKA1004").WithLocation(0).WithArguments("Holder");
		var hrk1008 = DiagnosticResult.CompilerError("HARUKA1008").WithLocation(0).WithArguments("Holder");
		await VerifyCS.VerifyAsync(TestContext.Current.CancellationToken, test, [], [ hrk1003, hrk1008 ]);
	}

	[Fact]
	public async Task HARUKA1008HasStaticPartialMethod()
	{
		var test =
@"using Microsoft.Extensions.DependencyInjection;
using Haruka.Attributes;

namespace Haruka.Generated.Tests;

[HarukaRegisterationHolder]
public static class {|#0:HarukaHolder|}
{
	public static partial void {|#1:GeneratedRegisterServices|}(this IServiceCollection services);
}";

		var hrk1008 = DiagnosticResult.CompilerError("HARUKA1008").WithLocation(0).WithArguments("HarukaHolder");
		var cs0751 = DiagnosticResult.CompilerError("CS0751").WithLocation(1);
		var cs8795 = DiagnosticResult.CompilerError("CS8795").WithLocation(1);
		await VerifyCS.VerifyAsync(TestContext.Current.CancellationToken, test, [], hrk1008, cs0751, cs8795);
	}

	[Fact]
	public async Task GeneratedMethodNotPartial()
	{
		var test =
@"using Microsoft.Extensions.DependencyInjection;
using Haruka.Attributes;

namespace Haruka.Generated.Tests;

[HarukaRegisterationHolder]
public static partial class {|#0:HarukaHolder|}
{
	public static void {|#1:GeneratedRegisterServices|}(this IServiceCollection services)
	{ }
}";

		var hrk1003 = DiagnosticResult.CompilerError("HARUKA1003").WithLocation(0).WithArguments("HarukaHolder");
		var hrk1004 = DiagnosticResult.CompilerError("HARUKA1004").WithLocation(0).WithLocation(1).WithArguments("HarukaHolder");
		await VerifyCS.VerifyAsync(TestContext.Current.CancellationToken, test, [], hrk1003, hrk1004);
	}

	[Fact]
	public async Task GeneratedMethodAlreadyDefined()
	{
		var test =
@"using Microsoft.Extensions.DependencyInjection;
using Haruka.Attributes;

namespace Haruka.Generated.Tests;

[HarukaRegisterationHolder]
public static partial class {|#0:HarukaHolder|}
{
	public static partial void {|#1:GeneratedRegisterServices|}(this IServiceCollection services);

	public static partial void {|#2:GeneratedRegisterServices|}(this IServiceCollection services)
	{ }
}";

		var hrk1006 = DiagnosticResult.CompilerError("HARUKA1006").WithLocation(2).WithArguments("HarukaHolder");
		var hrk1004 = DiagnosticResult.CompilerError("HARUKA1004").WithLocation(0).WithArguments("HarukaHolder");
		await VerifyCS.VerifyAsync(TestContext.Current.CancellationToken, test, [], hrk1006, hrk1004);
	}

	[Fact]
	public async Task GeneratedMethodNotStatic()
	{
		var test =
@"using Microsoft.Extensions.DependencyInjection;
using Haruka.Attributes;

namespace Haruka.Generated.Tests;

[HarukaRegisterationHolder]
public partial class {|#0:HarukaHolder|}
{
	public partial void {|#1:GeneratedRegisterServices|}(IServiceCollection services);
}";

		var hrk1003 = DiagnosticResult.CompilerError("HARUKA1002").WithLocation(0).WithArguments("HarukaHolder");
		var hrk1004 = DiagnosticResult.CompilerError("HARUKA1004").WithLocation(0).WithLocation(1).WithArguments("HarukaHolder");
		var cs8795 = DiagnosticResult.CompilerError("CS8795").WithLocation(1);
		await VerifyCS.VerifyAsync(TestContext.Current.CancellationToken, test, [], hrk1003, hrk1004, cs8795);
	}
}
